type FoodSeed = {
  source: 'taco';
  name: string;
  category: string;
  calories_kcal: number;
  protein_g: number;
  carbs_g: number;
  fats_g: number;
  fiber_g: number;
  sodium_mg: number;
  serving_size_g?: number;
  serving_description?: string;
};

export const foods: FoodSeed[] = [
  // PROTEÍNAS ANIMAIS (30)
  { source: 'taco', name: 'Peito de frango grelhado', category: 'protein', calories_kcal: 163, protein_g: 31, carbs_g: 0, fats_g: 3.6, fiber_g: 0, sodium_mg: 74 },
  { source: 'taco', name: 'Coxa de frango cozida', category: 'protein', calories_kcal: 215, protein_g: 27, carbs_g: 0, fats_g: 11, fiber_g: 0, sodium_mg: 85 },
  { source: 'taco', name: 'Sobrecoxa de frango', category: 'protein', calories_kcal: 223, protein_g: 26, carbs_g: 0, fats_g: 13, fiber_g: 0, sodium_mg: 80 },
  { source: 'taco', name: 'Contrafilé grelhado', category: 'protein', calories_kcal: 217, protein_g: 32, carbs_g: 0, fats_g: 9, fiber_g: 0, sodium_mg: 55 },
  { source: 'taco', name: 'Patinho cozido', category: 'protein', calories_kcal: 219, protein_g: 35, carbs_g: 0, fats_g: 8, fiber_g: 0, sodium_mg: 52 },
  { source: 'taco', name: 'Alcatra grelhada', category: 'protein', calories_kcal: 212, protein_g: 32, carbs_g: 0, fats_g: 9, fiber_g: 0, sodium_mg: 50 },
  { source: 'taco', name: 'Picanha grelhada', category: 'protein', calories_kcal: 289, protein_g: 26, carbs_g: 0, fats_g: 20, fiber_g: 0, sodium_mg: 58 },
  { source: 'taco', name: 'Costela bovina assada', category: 'protein', calories_kcal: 370, protein_g: 22, carbs_g: 0, fats_g: 31, fiber_g: 0, sodium_mg: 70 },
  { source: 'taco', name: 'Músculo bovino cozido', category: 'protein', calories_kcal: 195, protein_g: 34, carbs_g: 0, fats_g: 6, fiber_g: 0, sodium_mg: 54 },
  { source: 'taco', name: 'Filé mignon grelhado', category: 'protein', calories_kcal: 220, protein_g: 32, carbs_g: 0, fats_g: 10, fiber_g: 0, sodium_mg: 55 },
  { source: 'taco', name: 'Tilápia grelhada', category: 'protein', calories_kcal: 129, protein_g: 26, carbs_g: 0, fats_g: 2.7, fiber_g: 0, sodium_mg: 52 },
  { source: 'taco', name: 'Salmão grelhado', category: 'protein', calories_kcal: 208, protein_g: 22, carbs_g: 0, fats_g: 13, fiber_g: 0, sodium_mg: 59 },
  { source: 'taco', name: 'Sardinha em lata', category: 'protein', calories_kcal: 208, protein_g: 25, carbs_g: 0, fats_g: 11, fiber_g: 0, sodium_mg: 307 },
  { source: 'taco', name: 'Atum em lata conservado em água', category: 'protein', calories_kcal: 116, protein_g: 26, carbs_g: 0, fats_g: 1, fiber_g: 0, sodium_mg: 247 },
  { source: 'taco', name: 'Bacalhau dessalgado cozido', category: 'protein', calories_kcal: 108, protein_g: 22, carbs_g: 0, fats_g: 1.7, fiber_g: 0, sodium_mg: 205 },
  { source: 'taco', name: 'Camarão cozido', category: 'protein', calories_kcal: 99, protein_g: 24, carbs_g: 0, fats_g: 0.3, fiber_g: 0, sodium_mg: 111 },
  { source: 'taco', name: 'Ovo de galinha inteiro cozido', category: 'protein', calories_kcal: 146, protein_g: 13, carbs_g: 0.6, fats_g: 10, fiber_g: 0, sodium_mg: 142, serving_size_g: 50, serving_description: '1 unidade' },
  { source: 'taco', name: 'Clara de ovo cozida', category: 'protein', calories_kcal: 52, protein_g: 11, carbs_g: 0.7, fats_g: 0.2, fiber_g: 0, sodium_mg: 166, serving_size_g: 33, serving_description: '1 clara' },
  { source: 'taco', name: 'Gema de ovo cozida', category: 'protein', calories_kcal: 353, protein_g: 16, carbs_g: 0.6, fats_g: 32, fiber_g: 0, sodium_mg: 51, serving_size_g: 17, serving_description: '1 gema' },
  { source: 'taco', name: 'Peito de peru defumado', category: 'protein', calories_kcal: 104, protein_g: 17, carbs_g: 2, fats_g: 3, fiber_g: 0, sodium_mg: 827 },
  { source: 'taco', name: 'Bacon frito', category: 'protein', calories_kcal: 541, protein_g: 37, carbs_g: 1.4, fats_g: 42, fiber_g: 0, sodium_mg: 1717 },
  { source: 'taco', name: 'Linguiça calabresa', category: 'protein', calories_kcal: 306, protein_g: 17, carbs_g: 1, fats_g: 26, fiber_g: 0, sodium_mg: 1300 },
  { source: 'taco', name: 'Presunto cozido', category: 'protein', calories_kcal: 116, protein_g: 17, carbs_g: 2, fats_g: 4, fiber_g: 0, sodium_mg: 1200 },
  { source: 'taco', name: 'Queijo minas frescal', category: 'dairy', calories_kcal: 264, protein_g: 17, carbs_g: 3, fats_g: 20, fiber_g: 0, sodium_mg: 35 },
  { source: 'taco', name: 'Queijo mussarela', category: 'dairy', calories_kcal: 330, protein_g: 22, carbs_g: 3, fats_g: 25, fiber_g: 0, sodium_mg: 627 },
  { source: 'taco', name: 'Queijo prato', category: 'dairy', calories_kcal: 360, protein_g: 23, carbs_g: 1.6, fats_g: 29, fiber_g: 0, sodium_mg: 512 },
  { source: 'taco', name: 'Queijo cottage', category: 'dairy', calories_kcal: 92, protein_g: 11, carbs_g: 3, fats_g: 4, fiber_g: 0, sodium_mg: 364 },
  { source: 'taco', name: 'Requeijão cremoso', category: 'dairy', calories_kcal: 257, protein_g: 9.5, carbs_g: 3, fats_g: 23, fiber_g: 0, sodium_mg: 635 },
  { source: 'taco', name: 'Iogurte natural integral', category: 'dairy', calories_kcal: 61, protein_g: 3.5, carbs_g: 4.7, fats_g: 3.3, fiber_g: 0, sodium_mg: 46 },
  { source: 'taco', name: 'Leite integral', category: 'dairy', calories_kcal: 61, protein_g: 3.2, carbs_g: 4.7, fats_g: 3.3, fiber_g: 0, sodium_mg: 49 },

  // CARBOIDRATOS (30)
  { source: 'taco', name: 'Arroz branco cozido', category: 'carb', calories_kcal: 128, protein_g: 2.5, carbs_g: 28, fats_g: 0.2, fiber_g: 1.6, sodium_mg: 1 },
  { source: 'taco', name: 'Arroz integral cozido', category: 'carb', calories_kcal: 124, protein_g: 2.6, carbs_g: 26, fats_g: 1, fiber_g: 2.7, sodium_mg: 1 },
  { source: 'taco', name: 'Feijão carioca cozido', category: 'carb', calories_kcal: 76, protein_g: 4.8, carbs_g: 13.6, fats_g: 0.5, fiber_g: 8.5, sodium_mg: 2 },
  { source: 'taco', name: 'Feijão preto cozido', category: 'carb', calories_kcal: 77, protein_g: 4.5, carbs_g: 14, fats_g: 0.5, fiber_g: 8.4, sodium_mg: 2 },
  { source: 'taco', name: 'Lentilha cozida', category: 'carb', calories_kcal: 93, protein_g: 6.3, carbs_g: 16, fats_g: 0.5, fiber_g: 7.9, sodium_mg: 2 },
  { source: 'taco', name: 'Grão-de-bico cozido', category: 'carb', calories_kcal: 121, protein_g: 7, carbs_g: 20, fats_g: 2.4, fiber_g: 6, sodium_mg: 2 },
  { source: 'taco', name: 'Batata inglesa cozida', category: 'carb', calories_kcal: 52, protein_g: 1.2, carbs_g: 11.9, fats_g: 0, fiber_g: 1.3, sodium_mg: 2 },
  { source: 'taco', name: 'Batata doce cozida', category: 'carb', calories_kcal: 77, protein_g: 0.6, carbs_g: 18.4, fats_g: 0.1, fiber_g: 2.2, sodium_mg: 9 },
  { source: 'taco', name: 'Mandioca cozida', category: 'carb', calories_kcal: 125, protein_g: 0.6, carbs_g: 30, fats_g: 0.3, fiber_g: 1.6, sodium_mg: 1 },
  { source: 'taco', name: 'Mandioquinha cozida', category: 'carb', calories_kcal: 67, protein_g: 1, carbs_g: 15, fats_g: 0.1, fiber_g: 1.9, sodium_mg: 1 },
  { source: 'taco', name: 'Inhame cozido', category: 'carb', calories_kcal: 97, protein_g: 2.1, carbs_g: 23, fats_g: 0.2, fiber_g: 2.8, sodium_mg: 1 },
  { source: 'taco', name: 'Macarrão cozido', category: 'carb', calories_kcal: 157, protein_g: 5.8, carbs_g: 31, fats_g: 0.9, fiber_g: 1.8, sodium_mg: 1 },
  { source: 'taco', name: 'Pão francês', category: 'carb', calories_kcal: 300, protein_g: 8, carbs_g: 59, fats_g: 3.1, fiber_g: 2.3, sodium_mg: 648, serving_size_g: 50, serving_description: '1 unidade' },
  { source: 'taco', name: 'Pão de forma integral', category: 'carb', calories_kcal: 253, protein_g: 9.4, carbs_g: 47, fats_g: 3.5, fiber_g: 6.9, sodium_mg: 556, serving_size_g: 25, serving_description: '1 fatia' },
  { source: 'taco', name: 'Tapioca', category: 'carb', calories_kcal: 240, protein_g: 0, carbs_g: 60, fats_g: 0, fiber_g: 0.3, sodium_mg: 2 },
  { source: 'taco', name: 'Aveia em flocos', category: 'carb', calories_kcal: 394, protein_g: 13.9, carbs_g: 66.6, fats_g: 8.5, fiber_g: 9.1, sodium_mg: 5 },
  { source: 'taco', name: 'Granola', category: 'carb', calories_kcal: 471, protein_g: 13, carbs_g: 64, fats_g: 18, fiber_g: 7, sodium_mg: 30 },
  { source: 'taco', name: 'Farinha de aveia', category: 'carb', calories_kcal: 404, protein_g: 14, carbs_g: 69, fats_g: 7, fiber_g: 9, sodium_mg: 5 },
  { source: 'taco', name: 'Quinoa cozida', category: 'carb', calories_kcal: 120, protein_g: 4.4, carbs_g: 21, fats_g: 1.9, fiber_g: 2.8, sodium_mg: 7 },
  { source: 'taco', name: 'Polenta cozida', category: 'carb', calories_kcal: 85, protein_g: 2, carbs_g: 18, fats_g: 0.5, fiber_g: 1.5, sodium_mg: 2 },
  { source: 'taco', name: 'Cuscuz de milho', category: 'carb', calories_kcal: 113, protein_g: 2.4, carbs_g: 25, fats_g: 0.3, fiber_g: 1.9, sodium_mg: 1 },
  { source: 'taco', name: 'Milho verde cozido', category: 'carb', calories_kcal: 98, protein_g: 3.3, carbs_g: 22, fats_g: 1.3, fiber_g: 3.9, sodium_mg: 3 },
  { source: 'taco', name: 'Biscoito cream cracker', category: 'carb', calories_kcal: 432, protein_g: 11, carbs_g: 68, fats_g: 14, fiber_g: 2.4, sodium_mg: 846 },
  { source: 'taco', name: 'Biscoito recheado chocolate', category: 'carb', calories_kcal: 472, protein_g: 5.4, carbs_g: 72, fats_g: 18, fiber_g: 2, sodium_mg: 285 },
  { source: 'taco', name: 'Bolo simples', category: 'carb', calories_kcal: 346, protein_g: 6, carbs_g: 52, fats_g: 13, fiber_g: 1, sodium_mg: 310 },
  { source: 'taco', name: 'Pão de queijo', category: 'carb', calories_kcal: 363, protein_g: 6, carbs_g: 36, fats_g: 22, fiber_g: 0.5, sodium_mg: 645 },
  { source: 'taco', name: 'Angu de milho', category: 'carb', calories_kcal: 87, protein_g: 2, carbs_g: 18, fats_g: 0.5, fiber_g: 1.2, sodium_mg: 150 },
  { source: 'taco', name: 'Farofa pronta', category: 'carb', calories_kcal: 406, protein_g: 3, carbs_g: 76, fats_g: 10, fiber_g: 5, sodium_mg: 360 },
  { source: 'taco', name: 'Tapioca goma hidratada', category: 'carb', calories_kcal: 210, protein_g: 0.2, carbs_g: 52, fats_g: 0.1, fiber_g: 0, sodium_mg: 1 },
  { source: 'taco', name: 'Pão doce', category: 'carb', calories_kcal: 303, protein_g: 8, carbs_g: 56, fats_g: 5, fiber_g: 2, sodium_mg: 320 },

  // FRUTAS (25)
  { source: 'taco', name: 'Banana prata', category: 'fruit', calories_kcal: 98, protein_g: 1.3, carbs_g: 26, fats_g: 0.1, fiber_g: 2, sodium_mg: 1, serving_size_g: 86, serving_description: '1 unidade média' },
  { source: 'taco', name: 'Banana nanica', category: 'fruit', calories_kcal: 92, protein_g: 1.4, carbs_g: 23.8, fats_g: 0.1, fiber_g: 1.9, sodium_mg: 1 },
  { source: 'taco', name: 'Maçã fuji', category: 'fruit', calories_kcal: 56, protein_g: 0.3, carbs_g: 15, fats_g: 0.2, fiber_g: 2, sodium_mg: 1, serving_size_g: 150, serving_description: '1 unidade média' },
  { source: 'taco', name: 'Maçã verde', category: 'fruit', calories_kcal: 52, protein_g: 0.3, carbs_g: 14, fats_g: 0.2, fiber_g: 2.4, sodium_mg: 1 },
  { source: 'taco', name: 'Laranja pera', category: 'fruit', calories_kcal: 37, protein_g: 1, carbs_g: 8.7, fats_g: 0.1, fiber_g: 1.8, sodium_mg: 1 },
  { source: 'taco', name: 'Mamão papaia', category: 'fruit', calories_kcal: 40, protein_g: 0.5, carbs_g: 10, fats_g: 0.1, fiber_g: 1.8, sodium_mg: 3 },
  { source: 'taco', name: 'Mamão formosa', category: 'fruit', calories_kcal: 45, protein_g: 0.8, carbs_g: 11, fats_g: 0.1, fiber_g: 1, sodium_mg: 3 },
  { source: 'taco', name: 'Abacaxi', category: 'fruit', calories_kcal: 48, protein_g: 0.9, carbs_g: 12, fats_g: 0.1, fiber_g: 1, sodium_mg: 1 },
  { source: 'taco', name: 'Manga', category: 'fruit', calories_kcal: 64, protein_g: 0.4, carbs_g: 16, fats_g: 0.2, fiber_g: 2.1, sodium_mg: 1 },
  { source: 'taco', name: 'Uva', category: 'fruit', calories_kcal: 53, protein_g: 0.7, carbs_g: 13, fats_g: 0.2, fiber_g: 0.9, sodium_mg: 1 },
  { source: 'taco', name: 'Melancia', category: 'fruit', calories_kcal: 33, protein_g: 0.9, carbs_g: 8, fats_g: 0.2, fiber_g: 0.1, sodium_mg: 1 },
  { source: 'taco', name: 'Melão', category: 'fruit', calories_kcal: 29, protein_g: 0.7, carbs_g: 7, fats_g: 0.2, fiber_g: 0.3, sodium_mg: 12 },
  { source: 'taco', name: 'Morango', category: 'fruit', calories_kcal: 30, protein_g: 0.9, carbs_g: 6.8, fats_g: 0.3, fiber_g: 1.7, sodium_mg: 1 },
  { source: 'taco', name: 'Kiwi', category: 'fruit', calories_kcal: 51, protein_g: 1.1, carbs_g: 12, fats_g: 0.5, fiber_g: 2.7, sodium_mg: 3 },
  { source: 'taco', name: 'Pera', category: 'fruit', calories_kcal: 53, protein_g: 0.4, carbs_g: 14, fats_g: 0.2, fiber_g: 3.1, sodium_mg: 1 },
  { source: 'taco', name: 'Pêssego', category: 'fruit', calories_kcal: 36, protein_g: 0.8, carbs_g: 9, fats_g: 0.1, fiber_g: 1.4, sodium_mg: 1 },
  { source: 'taco', name: 'Goiaba', category: 'fruit', calories_kcal: 52, protein_g: 0.9, carbs_g: 13, fats_g: 0.5, fiber_g: 6.2, sodium_mg: 1 },
  { source: 'taco', name: 'Maracujá', category: 'fruit', calories_kcal: 68, protein_g: 2, carbs_g: 12, fats_g: 2, fiber_g: 1.1, sodium_mg: 28 },
  { source: 'taco', name: 'Acerola', category: 'fruit', calories_kcal: 33, protein_g: 0.9, carbs_g: 8, fats_g: 0.2, fiber_g: 1.5, sodium_mg: 7 },
  { source: 'taco', name: 'Caqui', category: 'fruit', calories_kcal: 71, protein_g: 0.4, carbs_g: 19, fats_g: 0.1, fiber_g: 6.5, sodium_mg: 1 },
  { source: 'taco', name: 'Abacate', category: 'fruit', calories_kcal: 96, protein_g: 1.2, carbs_g: 6, fats_g: 8.4, fiber_g: 6.3, sodium_mg: 1 },
  { source: 'taco', name: 'Coco ralado fresco', category: 'fruit', calories_kcal: 406, protein_g: 3.3, carbs_g: 11, fats_g: 42, fiber_g: 5.4, sodium_mg: 39 },
  { source: 'taco', name: 'Ameixa', category: 'fruit', calories_kcal: 53, protein_g: 0.8, carbs_g: 13, fats_g: 0.4, fiber_g: 2.4, sodium_mg: 1 },
  { source: 'taco', name: 'Figo', category: 'fruit', calories_kcal: 41, protein_g: 0.9, carbs_g: 10, fats_g: 0.2, fiber_g: 1.7, sodium_mg: 1 },
  { source: 'taco', name: 'Cereja', category: 'fruit', calories_kcal: 63, protein_g: 1.1, carbs_g: 16, fats_g: 0.2, fiber_g: 2.1, sodium_mg: 1 },

  // LEGUMES E VERDURAS (30)
  { source: 'taco', name: 'Alface crespa', category: 'vegetable', calories_kcal: 11, protein_g: 1.3, carbs_g: 1.7, fats_g: 0.2, fiber_g: 1.8, sodium_mg: 7 },
  { source: 'taco', name: 'Rúcula', category: 'vegetable', calories_kcal: 25, protein_g: 2.6, carbs_g: 3.7, fats_g: 0.7, fiber_g: 1.6, sodium_mg: 27 },
  { source: 'taco', name: 'Agrião', category: 'vegetable', calories_kcal: 17, protein_g: 2.7, carbs_g: 2.3, fats_g: 0.2, fiber_g: 2.1, sodium_mg: 14 },
  { source: 'taco', name: 'Espinafre cozido', category: 'vegetable', calories_kcal: 23, protein_g: 2.9, carbs_g: 3.8, fats_g: 0.4, fiber_g: 2.2, sodium_mg: 70 },
  { source: 'taco', name: 'Couve refogada', category: 'vegetable', calories_kcal: 90, protein_g: 2.9, carbs_g: 8, fats_g: 6, fiber_g: 3.4, sodium_mg: 160 },
  { source: 'taco', name: 'Repolho cru', category: 'vegetable', calories_kcal: 25, protein_g: 1.3, carbs_g: 5.8, fats_g: 0.1, fiber_g: 2.5, sodium_mg: 18 },
  { source: 'taco', name: 'Acelga', category: 'vegetable', calories_kcal: 19, protein_g: 1.8, carbs_g: 3.7, fats_g: 0.2, fiber_g: 1.6, sodium_mg: 213 },
  { source: 'taco', name: 'Brócolis cozido', category: 'vegetable', calories_kcal: 25, protein_g: 2.1, carbs_g: 4.4, fats_g: 0.4, fiber_g: 3.4, sodium_mg: 22 },
  { source: 'taco', name: 'Couve-flor cozida', category: 'vegetable', calories_kcal: 19, protein_g: 1.2, carbs_g: 4, fats_g: 0.3, fiber_g: 1.5, sodium_mg: 9 },
  { source: 'taco', name: 'Pepino', category: 'vegetable', calories_kcal: 10, protein_g: 0.9, carbs_g: 2, fats_g: 0.1, fiber_g: 0.6, sodium_mg: 3 },
  { source: 'taco', name: 'Tomate', category: 'vegetable', calories_kcal: 15, protein_g: 1.1, carbs_g: 3.1, fats_g: 0.2, fiber_g: 1.2, sodium_mg: 4 },
  { source: 'taco', name: 'Cenoura crua', category: 'vegetable', calories_kcal: 34, protein_g: 1.3, carbs_g: 7.7, fats_g: 0.2, fiber_g: 3.2, sodium_mg: 65 },
  { source: 'taco', name: 'Beterraba cozida', category: 'vegetable', calories_kcal: 32, protein_g: 1.3, carbs_g: 7.2, fats_g: 0.1, fiber_g: 1.9, sodium_mg: 53 },
  { source: 'taco', name: 'Abobrinha cozida', category: 'vegetable', calories_kcal: 12, protein_g: 1, carbs_g: 2.5, fats_g: 0.1, fiber_g: 1.3, sodium_mg: 2 },
  { source: 'taco', name: 'Berinjela cozida', category: 'vegetable', calories_kcal: 24, protein_g: 1.1, carbs_g: 5.7, fats_g: 0.2, fiber_g: 2.5, sodium_mg: 2 },
  { source: 'taco', name: 'Abóbora cozida', category: 'vegetable', calories_kcal: 38, protein_g: 1, carbs_g: 8, fats_g: 0.2, fiber_g: 2, sodium_mg: 1 },
  { source: 'taco', name: 'Pimentão verde', category: 'vegetable', calories_kcal: 21, protein_g: 1.1, carbs_g: 4.9, fats_g: 0.3, fiber_g: 2.6, sodium_mg: 2 },
  { source: 'taco', name: 'Pimentão vermelho', category: 'vegetable', calories_kcal: 28, protein_g: 1.2, carbs_g: 5.8, fats_g: 0.3, fiber_g: 1.6, sodium_mg: 2 },
  { source: 'taco', name: 'Cebola crua', category: 'vegetable', calories_kcal: 39, protein_g: 1.7, carbs_g: 8.9, fats_g: 0.1, fiber_g: 2.2, sodium_mg: 3 },
  { source: 'taco', name: 'Alho cru', category: 'vegetable', calories_kcal: 113, protein_g: 7, carbs_g: 23.9, fats_g: 0.2, fiber_g: 4.3, sodium_mg: 5 },
  { source: 'taco', name: 'Cogumelo paris', category: 'vegetable', calories_kcal: 22, protein_g: 3.1, carbs_g: 3.3, fats_g: 0.3, fiber_g: 1, sodium_mg: 5 },
  { source: 'taco', name: 'Cogumelo shiitake', category: 'vegetable', calories_kcal: 34, protein_g: 2.2, carbs_g: 6.8, fats_g: 0.5, fiber_g: 2.5, sodium_mg: 9 },
  { source: 'taco', name: 'Quiabo cozido', category: 'vegetable', calories_kcal: 23, protein_g: 1.7, carbs_g: 4.6, fats_g: 0.1, fiber_g: 3.9, sodium_mg: 8 },
  { source: 'taco', name: 'Vagem cozida', category: 'vegetable', calories_kcal: 28, protein_g: 2, carbs_g: 6, fats_g: 0.1, fiber_g: 2.8, sodium_mg: 4 },
  { source: 'taco', name: 'Chuchu cozido', category: 'vegetable', calories_kcal: 17, protein_g: 0.6, carbs_g: 4, fats_g: 0.1, fiber_g: 1.5, sodium_mg: 2 },
  { source: 'taco', name: 'Nabo cozido', category: 'vegetable', calories_kcal: 22, protein_g: 0.8, carbs_g: 5, fats_g: 0.1, fiber_g: 1.9, sodium_mg: 20 },
  { source: 'taco', name: 'Rabanete', category: 'vegetable', calories_kcal: 18, protein_g: 1, carbs_g: 3.9, fats_g: 0.1, fiber_g: 1.6, sodium_mg: 14 },
  { source: 'taco', name: 'Palmito em conserva', category: 'vegetable', calories_kcal: 26, protein_g: 2, carbs_g: 4.6, fats_g: 0.5, fiber_g: 2.5, sodium_mg: 530 },
  { source: 'taco', name: 'Aspargo cozido', category: 'vegetable', calories_kcal: 22, protein_g: 2.4, carbs_g: 4.1, fats_g: 0.2, fiber_g: 2.1, sodium_mg: 2 },
  { source: 'taco', name: 'Aipo cru', category: 'vegetable', calories_kcal: 16, protein_g: 0.7, carbs_g: 3, fats_g: 0.2, fiber_g: 1.6, sodium_mg: 80 },

  // GORDURAS E OLEAGINOSAS (15)
  { source: 'taco', name: 'Azeite de oliva extra virgem', category: 'fat', calories_kcal: 884, protein_g: 0, carbs_g: 0, fats_g: 100, fiber_g: 0, sodium_mg: 2 },
  { source: 'taco', name: 'Óleo de soja', category: 'fat', calories_kcal: 884, protein_g: 0, carbs_g: 0, fats_g: 100, fiber_g: 0, sodium_mg: 0 },
  { source: 'taco', name: 'Óleo de coco', category: 'fat', calories_kcal: 892, protein_g: 0, carbs_g: 0, fats_g: 100, fiber_g: 0, sodium_mg: 0 },
  { source: 'taco', name: 'Manteiga com sal', category: 'fat', calories_kcal: 726, protein_g: 0.4, carbs_g: 0.1, fats_g: 82, fiber_g: 0, sodium_mg: 579 },
  { source: 'taco', name: 'Margarina vegetal', category: 'fat', calories_kcal: 596, protein_g: 0.3, carbs_g: 0.7, fats_g: 65, fiber_g: 0, sodium_mg: 600 },
  { source: 'taco', name: 'Castanha do Pará', category: 'fat', calories_kcal: 643, protein_g: 14.5, carbs_g: 15, fats_g: 63, fiber_g: 7.9, sodium_mg: 3 },
  { source: 'taco', name: 'Castanha de caju', category: 'fat', calories_kcal: 570, protein_g: 18.5, carbs_g: 29, fats_g: 46, fiber_g: 3.7, sodium_mg: 16 },
  { source: 'taco', name: 'Amêndoa', category: 'fat', calories_kcal: 581, protein_g: 20, carbs_g: 20, fats_g: 50, fiber_g: 11, sodium_mg: 3 },
  { source: 'taco', name: 'Amendoim torrado', category: 'fat', calories_kcal: 544, protein_g: 27, carbs_g: 20, fats_g: 43, fiber_g: 8, sodium_mg: 5 },
  { source: 'taco', name: 'Nozes', category: 'fat', calories_kcal: 620, protein_g: 14, carbs_g: 18, fats_g: 59, fiber_g: 5.6, sodium_mg: 2 },
  { source: 'taco', name: 'Pasta de amendoim integral', category: 'fat', calories_kcal: 588, protein_g: 25, carbs_g: 20, fats_g: 50, fiber_g: 7, sodium_mg: 10 },
  { source: 'taco', name: 'Chia em grãos', category: 'fat', calories_kcal: 486, protein_g: 17, carbs_g: 42, fats_g: 31, fiber_g: 34, sodium_mg: 16 },
  { source: 'taco', name: 'Linhaça dourada', category: 'fat', calories_kcal: 534, protein_g: 18, carbs_g: 29, fats_g: 42, fiber_g: 27, sodium_mg: 30 },
  { source: 'taco', name: 'Gergelim', category: 'fat', calories_kcal: 573, protein_g: 18, carbs_g: 23, fats_g: 50, fiber_g: 11.8, sodium_mg: 11 },
  { source: 'taco', name: 'Cacau em pó 100%', category: 'fat', calories_kcal: 228, protein_g: 19.6, carbs_g: 58, fats_g: 13.7, fiber_g: 33, sodium_mg: 21 },

  // BEBIDAS E OUTROS (20)
  { source: 'taco', name: 'Café coado sem açúcar', category: 'drink', calories_kcal: 2, protein_g: 0.1, carbs_g: 0.3, fats_g: 0, fiber_g: 0, sodium_mg: 2 },
  { source: 'taco', name: 'Café com açúcar 1 colher', category: 'drink', calories_kcal: 20, protein_g: 0.1, carbs_g: 5, fats_g: 0, fiber_g: 0, sodium_mg: 2 },
  { source: 'taco', name: 'Leite com achocolatado', category: 'drink', calories_kcal: 76, protein_g: 3, carbs_g: 11, fats_g: 2.5, fiber_g: 0.2, sodium_mg: 50 },
  { source: 'taco', name: 'Suco de laranja natural', category: 'drink', calories_kcal: 41, protein_g: 0.7, carbs_g: 9.3, fats_g: 0.1, fiber_g: 0.2, sodium_mg: 1 },
  { source: 'taco', name: 'Suco de limão natural', category: 'drink', calories_kcal: 25, protein_g: 0.4, carbs_g: 8, fats_g: 0.1, fiber_g: 0.2, sodium_mg: 1 },
  { source: 'taco', name: 'Refrigerante cola', category: 'drink', calories_kcal: 42, protein_g: 0, carbs_g: 10.6, fats_g: 0, fiber_g: 0, sodium_mg: 4 },
  { source: 'taco', name: 'Refrigerante guaraná', category: 'drink', calories_kcal: 44, protein_g: 0, carbs_g: 11, fats_g: 0, fiber_g: 0, sodium_mg: 2 },
  { source: 'taco', name: 'Água de coco', category: 'drink', calories_kcal: 22, protein_g: 0.1, carbs_g: 5.3, fats_g: 0, fiber_g: 0.1, sodium_mg: 14 },
  { source: 'taco', name: 'Cerveja pilsen', category: 'drink', calories_kcal: 41, protein_g: 0.5, carbs_g: 3.2, fats_g: 0, fiber_g: 0, sodium_mg: 4 },
  { source: 'taco', name: 'Vinho tinto seco', category: 'drink', calories_kcal: 85, protein_g: 0.1, carbs_g: 2.6, fats_g: 0, fiber_g: 0, sodium_mg: 4 },
  { source: 'taco', name: 'Chá mate', category: 'drink', calories_kcal: 2, protein_g: 0, carbs_g: 0.5, fats_g: 0, fiber_g: 0, sodium_mg: 4 },
  { source: 'taco', name: 'Isotônico sabor uva', category: 'drink', calories_kcal: 26, protein_g: 0, carbs_g: 6.4, fats_g: 0, fiber_g: 0, sodium_mg: 55 },
  { source: 'taco', name: 'Whey protein isolado', category: 'supplement', calories_kcal: 370, protein_g: 85, carbs_g: 6, fats_g: 3, fiber_g: 0, sodium_mg: 300, serving_size_g: 30, serving_description: '1 scoop' },
  { source: 'taco', name: 'Barra de cereal', category: 'supplement', calories_kcal: 375, protein_g: 6, carbs_g: 65, fats_g: 10, fiber_g: 3, sodium_mg: 150, serving_size_g: 25, serving_description: '1 unidade' },
  { source: 'taco', name: 'Chocolate ao leite', category: 'sweet', calories_kcal: 540, protein_g: 7, carbs_g: 57, fats_g: 31, fiber_g: 2, sodium_mg: 79 },
  { source: 'taco', name: 'Chocolate 70% cacau', category: 'sweet', calories_kcal: 570, protein_g: 8, carbs_g: 35, fats_g: 43, fiber_g: 11, sodium_mg: 20 },
  { source: 'taco', name: 'Mel de abelha', category: 'sweet', calories_kcal: 309, protein_g: 0.5, carbs_g: 84, fats_g: 0, fiber_g: 0, sodium_mg: 7 },
  { source: 'taco', name: 'Açúcar refinado', category: 'sweet', calories_kcal: 387, protein_g: 0, carbs_g: 99.9, fats_g: 0, fiber_g: 0, sodium_mg: 0 },
  { source: 'taco', name: 'Açúcar mascavo', category: 'sweet', calories_kcal: 369, protein_g: 0.7, carbs_g: 95, fats_g: 0.1, fiber_g: 0, sodium_mg: 39 },
  { source: 'taco', name: 'Adoçante sucralose líquido', category: 'sweet', calories_kcal: 0, protein_g: 0, carbs_g: 0, fats_g: 0, fiber_g: 0, sodium_mg: 0 },
];
